spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore?useSSL=false
    username: springstudent
    password: springstudent
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true